name: mgcst_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8
  - streamlit
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - seaborn
  - plotly
  - statsmodels
  - openpyxl
  - pip :
    - streamlit_pdf_viewer
